### ISSUE TITLE
`toInvoice`/`checkSignature`/etc functions are not exportable

### ISSUE THREAD

**Issue by shalfey41** [sergeiivankov/crypto-bot-api#2]
Hey, @sergeiivankov! Thank you for this amazing library!

I'm using your SDK with NextJS and found an issue with exporting functions. 

So, I'm able to export helper functions like this.

```ts
import { toInvoice, checkSignature } from 'crypto-bot-api';
```

And I don't see any error. Moreover, IDE suggests these functions.

<img width="627" alt="Screenshot 2024-11-03 at 10 28 34 PM" src="https://github.com/user-attachments/assets/51c1f90c-6718-49a9-929d-0fd8d2c0c843">

<img width="718" alt="Screenshot 2024-11-03 at 10 28 48 PM" src="https://github.com/user-attachments/assets/08245369-87ef-4223-ae51-f772ede02950">

But when I try to use it, I see an error.

```bash
 ⨯ TypeError: (0 , crypto_bot_api__WEBPACK_IMPORTED_MODULE_2__.toInvoice) is not a function
    at $$ACTION_2 (./src/app/database/event/actions.ts:46:74)
digest: "4018400137"
  25 |
  26 | export const test1 = async (input: unknown) => {
> 27 |   console.log(toInvoice(input));
     |                         ^
  28 | };
```

Could you help here, please?

Thanks again. Your SDK has sped up my development process. It's really handy stuff!

**Comment by sergeiivankov** [comment]
Hello, @shalfey41! Sorry for long answer. I think it's because `toInvoice` and `checkSignature` functions are not exported by library. But it's exported in types declaration file to generate documentation, so your IDE propose it's import to you.

**Comment by sergeiivankov** [comment]
This functions are for internal usage. I see you need to use library with bundler, but library was written long time ago and not friendly with bundlers. But in next major version I plan to work on this point. Could you please describe your usage scenario in detail? It would help to make it better.

**Comment by shalfey41** [comment]
Sure!
The only reason I used `toInvoice` and `checkSignature` was dealing with webhooks. Here is what it looks like with NextJS.

```ts
import { checkSignature, toInvoice } from '@/modules/cryptopay/utils';

export const dynamic = 'force-dynamic';
export const fetchCache = 'force-no-store';

export const POST = async (request: Request) => {
  try {
    const body = await request.json();
    const isValidSignature = await checkSignature(
      request.headers.get('crypto-pay-api-signature') || '',
      body,
    );

    if (!isValidSignature) {
      throw new Error('Invalid signature');
    }

    const invoice = await toInvoice(body.payload);

    // do stuff with the invoice

    return Response.json({ success: true });
  } catch (error) {
    console.error(error);
    return Response.error();
  }
};
```

I don't have an exportable function from the library that can check the signature and transform the invoice, so I manually copied them from your library.

In terms of API, I love how [Grammy provides the webhookCallback function](https://grammy.dev/ref/core/webhookcallback). With their function, the code looks like this

```ts
export const POST = webhookCallback(bot, 'std/http');
```

Good luck with the new version and thank you!

**Comment by sergeiivankov** [comment]
Thank you! In library I create functional and examples for built in Node.js webserver and Express.js framework to receive webhooks from CryptoPay. It's good idea to export helpers function, so that people can use them with any framework. I will notify you when I release new version.
